# Generated by Django 4.1 on 2024-11-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Critica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('director', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Critica',
                'verbose_name_plural': 'Criticas',
            },
        ),
    ]
