# Generated by Django 4.1 on 2024-11-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticas', '0002_genero_remove_critica_genero_critica_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='critica',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
