# Generated by Django 4.1 on 2024-11-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticas', '0003_critica_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('genero', models.JSONField(help_text='Lista de géneros en formato JSON')),
                ('duracion', models.IntegerField(help_text='Duración en minutos')),
                ('director', models.CharField(max_length=100)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
            },
        ),
        migrations.DeleteModel(
            name='Critica',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
