# Generated by Django 4.1 on 2024-11-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticas', '0004_pelicula_delete_critica_delete_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(help_text='Lista de géneros separados por comas', max_length=255),
        ),
    ]
